version: '3'

dotenv:
  - .env

tasks:
  run:
    desc: Run the owuiback application
    cmd: go run cmd/owuiback/main.go {{.CLI_ARGS}}

  bootstrap:
    desc: Install project dependencies
    cmd: go mod download

  docker-build:
    desc: Build the Docker image
    cmd: docker build -t owuiback:latest .

  docker-run:
    desc: Build and run the application in Docker
    cmds:
      - docker build -t owuiback:latest .
      - docker run --rm owuiback:latest {{.CLI_ARGS}}

  build:
    desc: Build binaries for all platforms (Linux, macOS, Windows with amd64 and arm64)
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=amd64 go build -o dist/owuiback-linux-amd64 cmd/owuiback/main.go
      - GOOS=linux GOARCH=arm64 go build -o dist/owuiback-linux-arm64 cmd/owuiback/main.go
      - GOOS=darwin GOARCH=amd64 go build -o dist/owuiback-darwin-amd64 cmd/owuiback/main.go
      - GOOS=darwin GOARCH=arm64 go build -o dist/owuiback-darwin-arm64 cmd/owuiback/main.go
      - GOOS=windows GOARCH=amd64 go build -o dist/owuiback-windows-amd64.exe cmd/owuiback/main.go
      - GOOS=windows GOARCH=arm64 go build -o dist/owuiback-windows-arm64.exe cmd/owuiback/main.go
